# neo4j-chains

A collections of https://neo4j.com[neo4j] stored procedures to build character and/or token chains.

## available procedures

### thm.characterChain

.Parameters thm.characterChain
|===
| name | type | description | default value

| text | String | string to be used for building a chain of nodes |
| | | |
| return value | Path | a path holding the created chain |
|===

#### example

----
CALL thm.characterChain('what a nice text') YIELD path RETURN path;

match (t:Text) 
where t.text is not null
with t
call thm.characterChain(t.text) yield path return path;

----

### thm.tokenChain

Uses regex `((?<=\W)|(?=\W))` for identifying tokens.

.Parameters thm.tokenChain
|===
| name | type | description | default value

| text | String | string to be used for building a chain of nodes |
| | | |
| return value | Path | a path holding the created chain |
|===

#### examples

----
CALL thm.tokenChain('what a nice text') YIELD path RETURN path;
----

----
match (t:Text)
where t.text is not null
with t
call thm.tokenChain(t.text) yield path return path;
----

### thm.fullChain

The most complete procedure, creates both token and character chain.
Delegates internally to `thm.tokenChain` and `thm.characterChain`.
Interconnects the two chains appropriately.

.Parameters thm.fullChain
|===
| name | type | description | default value

| start | Node | start node holding the text in a property |
| propertyKey | string | property key |
| | | |
| return value | void ||
|===

#### example

----
CREATE (s:Text{text:'What a nice text'})
WITH s
CALL thm.fullChain(s, 'text')
RETURN s
----

### thm.chain

A very generic procedure to build a chain of nodes.

.Parameters thm.chain
|===
| name | type | description | default value

| text | string | string to be used for building a chain of nodes |
| regex | string | separator regex pattern |
| label | string | label for new nodes |
| relType | string | relationship type used for the chain |
| applyIndexProperties | boolean | whether to add startIndex/endIndex properties |
| | | |
| return value | Path | a path holding the created chain |
|===

NOTE: the regex parameter uses lookahead/lookbehind notation, see https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html

#### example

----
CALL thm.chain('what a nice text', '((?<=\\s)|(?=\\s))', 'Character', 'NEXT_CHARACTER', false) YIELD path RETURN path
----

#### create example

----
match (n) detach delete n;
create (t1:Text {text:'M端de macht uns die Arbeit, die wir liegen lassen, nicht die, die wir tun.', textEn:'It is the work we leave undone that makes us tired, not the work we do.', url:'https://klebeheld.de/wandtattoos/zitate/arbeit/wandtattoo-muede-macht-uns-die-arbeit-die-wir-liegen-lassen-nicht-die-die-wir-tun.-no.1-ebner-e/542'})
create (t2:Text {text:'M端de macht uns nicht die Arbeit die wir tun sondern die, die wir liegen lassen.', textEn:'It is not the work we do that makes us tired, but the work we leave undone.', url:'https://www.mak-uk.de/wir-ueber-uns-pd.html'});
// Create uuids f端r Character-Nodes
:auto MATCH (r:Character)
WHERE r.uuid is null
CALL {
WITH r
SET r.uuid = apoc.create.uuid()
} IN TRANSACTIONS OF 1000 ROWS
RETURN count(*);
// Create uuids f端r Token-Nodes
:auto MATCH (r:Token)
WHERE r.uuid is null
CALL {
WITH r
SET r.uuid = apoc.create.uuid()
} IN TRANSACTIONS OF 1000 ROWS
RETURN count(*);
----
