name: create-new-github-release

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version (prefix with "v")'
        required: true
        default: 'v0.4.8'
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ github.event.inputs.releaseversion }}
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Set projects Maven version to GitHub Action GUI set version
        run: mvn versions:set "-DnewVersion=${RELEASE_VERSION}" --no-transfer-progress

      - name: commit
        run: mvn versions:commit

      - name: Publish package
        run: mvn --batch-mode clean deploy --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: push version bump and tag
        run: |
          git config --global user.name 'THMGraph Bot'
          git config --global user.email "thmgraph@users.noreply.github.com"
          git diff --quiet || git commit -am "mvn version bump"
          git tag "${RELEASE_VERSION}"
          git push origin HEAD
          git push origin "${RELEASE_VERSION}"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.releaseversion }}
          generate_release_notes: true
          files: target/neo4j-atag-*.jar
          draft: false
          prerelease: false
